Ext.define('VIN.model.Produit', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'no_produit_interne', 
        type: 'int',
        useNull: true
    }, {
        name: 'ancien_no_produit', 
        type: 'int',
        useNull: true
    }, {             
        name: 'nom_producteur'
    }, {
        name: 'type_vin'
    }, {
        name: 'nom_domaine'
    }, {
        name: 'format',
    }, {
        name: 'couleur'
    }, {
        name: 'quantite_par_caisse',
        type: 'int'
    }, {
        name: 'pays'
    }, {
        name: 'suc_num',
        type: 'int',
        useNull: true
    }],
    idProperty: 'no_produit_interne'
});
